repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local  #Using local hook to use flake9 which allows for configs in pyproject.toml
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 src tests
        language: system
        pass_filenames: false
        always_run: true
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
