name: doc_build
on:
    push:
        branches: 
            - 'main'
        paths:
            - 'docs/**'
            - 'src/**'
            - '.github/workflows/doc_build.yml'

jobs: 
    build_docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out respository
              uses: actions/checkout@v3
            
            - name: Set up python
              id: setyp-python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install Poetry
              uses: snok/install-poetry@v1.3.3
              with:
                version: 1.4.2
            
            - name: Install Doc dependencies
              run: poetry install
              shell: bash
            
            - name: Make html
              run: |
                cd docs
                poetry run make clean html
                cd ..
            
            - name: Publish docs
              uses: peaceiris/actions-gh-pages@v3
              with:  
                publish_branch: gh-pages
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: docs/_build/html
                force_orphan: true


